### ISSUE TITLE
odysseyra1n-install.bash: line 12: /binpack/usr/bin/plutil: No such file or directory

### ISSUE THREAD

**Issue by 60ke** [coolstar/Odyssey-bootstrap#28]
when i run `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/coolstar/Odyssey-bootstrap/master/procursus-deploy-linux-macos.sh)"` 

some error occur：
```bash
It's recommended that this script be ran on macOS/Linux with a non-bootstrapped iOS device running checkra1n attached.
Press enter to continue

Odysseyra1n Installation Script
(C) 2021, CoolStar. All Rights Reserved

Before you begin: If you're currently jailbroken with a different bootstrap installed, you will need to Reset System via the Loader app before running this script.
Press enter to continue.

(1) Downloading resources...
(3) Bootstrapping your device...
odysseyra1n-install.bash: line 12: /binpack/usr/bin/plutil: No such file or directory
 not compatible.
```

my device:
MacBook Air (M1, 2020)
iphone7

**Comment by BLahz** [comment]
I encountered the same problem and fixed it by running my terminal (iTerm 2 in this case but any terminal should work) under rosetta. Go to applications folder -> right click on the app -> get info -> tick run under rosetta -> works
