### ISSUE TITLE
Anyway to make the script look for offline files?

### ISSUE THREAD

**Issue by sevenpastzeero** [coolstar/Odyssey-bootstrap#29]
I have a very bad, slow internet. And I was hoping to find a way to make the script look for 'bootstrap_1700.tar.gz' instead of downloading it every time I run it.

**Comment by raspberryenvoie** [comment]
1. Download the whole repository
2. Edit procursus-deploy-linux-mac.sh and remove the following lines :

`CURRENTDIR=$(pwd)`
`ODYSSEYDIR=$(mktemp -d)`
`cd "$ODYSSEYDIR"`
`	cd "$CURRENTDIR"`
`	rm -rf "$ODYSSEYDIR"`
And the one that starts with `curl`

3. Run procursus-deploy-linux-mac.sh and make sure you're inside the folder that contains the repository you downloaded

Hope it helps :)

**Comment by sevenpastzeero** [comment]
Thank you very much. This worked great.
