### ISSUE TITLE
Permission Denied when Typing 'alpine'

### ISSUE THREAD

**Issue by Red1860** [coolstar/Odyssey-bootstrap#3]
I Am Using iOS 13.5 iPhone 7 trying to install Chimera1n but it is saying permission denied when I am writing alpine as password. I didn't change the default password.
Also It Was Working Fine on iOS 13.4.1 Before..

**Comment by demhademha** [comment]
Reinstall ssh

**Comment by iMonZ** [comment]
which system are you using? MacOS or Linux?
And which Distribution or Version are you using?

**Comment by Rohan200220** [comment]
I am using macOS Catalina 10.15.5

**Comment by nudiar** [comment]
After running this script: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/coolstar/Odyssey-bootstrap/master/procursus-deploy-linux-macos.sh)"; the root default has been changed. "Alpine" doesn't work anymore.

**Comment by nudiar** [comment]
"It is more likely that direct root login is not allowed, this is usually set in the /etc/ssh/sshd_config file". How to access /etc/ssh/sshd_config without root login? Is it possible?

**Comment by iMonZ** [comment]
I have now the same problem but only after batchomatics broke my system (again) 
Have you tried restoring Original-fs with the checkra1n app?
