### ISSUE TITLE
Not working on M1 MacBook

### ISSUE THREAD

**Issue by uchks** [coolstar/Odyssey-bootstrap#48]
After looking at the issues, I still face the same issue as #28.
However, PR #40 is supposed to fix that issue. Unfortunately it doesn't.
After looking at what the PR did, I noticed this string: 
```if [ "$(SYSTEM_VERSION_COMPAT=1 sw_vers -productName)" != "Mac OS X" ];```

So I ran ```$(SYSTEM_VERSION_COMPAT=1 sw_vers -productName)``` and my output was `macOS`. So I changed != "Mac OS X" to "macOS" and that worked fine, until I reached near the end. Included is a screenshot, showing my macOS Version and whatnot, along with the errors I faced after correcting the sw_vers command.

<img width="682" alt="Screenshot 2022-10-02 at 5 16 33 PM" src="https://user-images.githubusercontent.com/38664452/193478698-5582a7f3-162b-4510-80e9-f61e28d09a40.png">

<img width="682" alt="Screenshot 2022-10-02 at 4 51 46 PM" src="https://user-images.githubusercontent.com/38664452/193478601-b0d02ffc-c0d5-48ca-96d7-e66344402c11.png">

**Comment by localdevice** [comment]
This fork fixes my issue: https://github.com/verygenericname/Odyssey-bootstrap/ (after changing `Mac OS X` to `macOS`)

Leaving this issue open for a proper fix, should be addressed.

**Comment by Syntax3r** [comment]
The same issue occur with me while running the script and the above suggestion worked but now stuck at 
``bash: /var/root/odysseyra1n-install.bash: No such file or directory
procursus-deploy-linux-macos.sh: line 125: kill: (3910) - No such process``
