### ISSUE TITLE
Ssh error

### ISSUE THREAD

**Issue by demhademha** [coolstar/Odyssey-bootstrap#5]
Hi, upon running the script I get the following error 
Ssh 127.0.0.1 port 4444 connection refused 
Thanks

**Comment by iMonZ** [comment]
try to open the checkra1n app and the close it immediately after that and try again

**Comment by iMonZ** [comment]
Does this fixed that?

**Comment by demhademha** [comment]
No. See https://github.com/libimobiledevice/libusbmuxd.git 
The latest commit should have fixed this issue, however I ran it on device. I’ll reopen this issue until it’s confirmed to be fixed
